sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk=2.0.28-1

# Don't run bundle install
install: echo "skip bundle install"

branches:
  only:
    - master
    - /^(?i:travis).*$/
    - /^(?i:feature).*$/
    - /^(?i:fix).*$/
    - /^(?i:release).*$/

services: docker

env:
  matrix:
    - INSTANCE=default12-ubuntu-14
    - INSTANCE=default12-ubuntu-16
    - INSTANCE=default12-debian-8
    - INSTANCE=default12-debian-9
    - INSTANCE=default12-centos-6
    - INSTANCE=default12-centos-7
    - INSTANCE=default12-amazon
    - INSTANCE=default13-ubuntu-14
    - INSTANCE=default13-ubuntu-16
    - INSTANCE=default13-debian-8
    - INSTANCE=default13-debian-9
    - INSTANCE=default13-centos-6
    - INSTANCE=default13-centos-7
    - INSTANCE=default13-amazon

script:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}
  - cat .kitchen/logs/kitchen.log

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/cookstyle --version
  - /opt/chefdk/embedded/bin/foodcritic --version


matrix:
  allow_failures:
    - env: INSTANCE=default12-ubuntu-14
    - env: INSTANCE=default12-ubuntu-16
    - env: INSTANCE=default12-debian-8
    - env: INSTANCE=default12-debian-9
    - env: INSTANCE=default12-centos-6
    - env: INSTANCE=default12-centos-7
    - env: INSTANCE=default12-amazon
    - env: INSTANCE=default13-ubuntu-14
    - env: INSTANCE=default13-ubuntu-16
    - env: INSTANCE=default13-debian-8
    - env: INSTANCE=default13-debian-9
    - env: INSTANCE=default13-centos-6
    - env: INSTANCE=default13-centos-7
    - env: INSTANCE=default13-amazon
  include:
    - script:
      - /opt/chefdk/bin/chef exec rake
      env: UNIT_AND_LINT=1
